### ISSUE TITLE
Receiving OPTIONS ERROR during POST 

### ISSUE THREAD

**Issue by SoroTrestal** [proudmonkey/AutoWrapper#16]
Hello, i am receiving an error during a post, it seems to happen during the options call:

Unhandled Exception occurred. Unable to process the request.
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 204.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowWritingToResponseBodyNotSupported()

Full stack trace:

```
2019-11-20 11:19:00,608 [59] INFO  Microsoft.AspNetCore.Hosting.Internal.WebHost - Request finished in 37.78ms 204 application/json
2019-11-20 11:19:00,632 [48] INFO  Microsoft.AspNetCore.Hosting.Internal.WebHost - Request starting HTTP/1.1 OPTIONS http://localhost/Elicio_Api/api/Project/list/  
2019-11-20 11:19:00,642 [48] INFO  Microsoft.AspNetCore.Cors.Infrastructure.CorsService - Policy execution successful.
2019-11-20 11:19:00,648 [48] ERROR AutoWrapper.AutoWrapperMiddleware - [500]: Unhandled Exception occurred. Unable to process the request.
System.InvalidOperationException: Writing to the response body is invalid for responses with status code 204.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowWritingToResponseBodyNotSupported()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WriteAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, CancellationToken cancellationToken)
   at AutoWrapper.AutoWrapperMembers.WriteFormattedResponseToHttpContext(HttpContext context, Int32 code, String jsonString, Boolean isError)
   at AutoWrapper.AutoWrapperMembers.HandleNotSuccessRequestAsync(HttpContext context, Object body, Int32 code)
   at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)
2019-11-20 11:19:00,654 [48] INFO  AutoWrapper.AutoWrapperMiddleware - Request: OPTIONS http localhost/api/Project/list/   Responded with [204] in 11ms
2019-11-20 11:19:00,660 [48] ERROR Microsoft.AspNetCore.Server.Kestrel - Connection id "0HLRDJUQ2J50D", Request id "0HLRDJUQ2J50D:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: StatusCode cannot be set because the response has already started.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowResponseAlreadyStartedException(String value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Microsoft.AspNetCore.Http.Features.IHttpResponseFeature.set_StatusCode(Int32 value)
   at Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse.set_StatusCode(Int32 value)
   at AutoWrapper.AutoWrapperMembers.WriteFormattedResponseToHttpContext(HttpContext context, Int32 code, String jsonString, Boolean isError)
   at AutoWrapper.AutoWrapperMembers.HandleExceptionAsync(HttpContext context, Exception exception)
   at AutoWrapper.Base.WrapperBase.InvokeAsyncBase(HttpContext context, AutoWrapperMembers awm)
   at AutoWrapper.AutoWrapperMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2019-11-20 11:19:00,665 [48] INFO  Microsoft.AspNetCore.Hosting.Internal.WebHost - Request finished in 34.248ms 204 application/json
```

I have managed to get around it by adding the following in de middleware class in the function: InvokeAsync

```
 else if (context.Response.StatusCode == 204) { }
```

Regards

**Comment by trinvh** [comment]
@SoroTrestal You need to make sure the CORs middleware is placed before AutoWrapper like this:

```
app.UseCors(...)
app.UseApiResponseAndExceptionWrapper(...)
```

This should be described in the documentation as well.

**Comment by proudmonkey** [comment]
@SoroTrestal - Sorry I didn't get the chance to look into this right away. I will verify this behavior this week and let you know.

@trinvh - Thanks for the tip! In the documentation I've stated that `AutoWrapper` should be registered **_before_** `UseRouting()` middleware. The UseCors() should be registered before both:

```csharp
app.UseCors(...);
//register other services here
app.UseApiResponseAndExceptionWrapper(...);
app.UseRouting();
```

**Comment by proudmonkey** [comment]
@SoroTrestal I can't seem to replicate the error in the latest version. Also does adding `CORS` before `AutoWrapper` resolves your issue?

**Comment by proudmonkey** [comment]
Closing this issue as I can't replace it. Feel free to reopen it if the issue still persist on your side and provide details. Thanks!
